version: 2

updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "emqtt"
      - dependency-name: "heroicons"
    reviewers:
      - "jhosteny"
      - "atcherry"
      - "itamm15"
    target-branch: "develop"
