name: Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/_build_and_test.yml
    secrets: inherit
